#!/bin/tcsh -f

setenv OPTIONS "-cps-evaluator -lazy-map-closure"
unlimit stack
echo Example 1
mzscheme <<EOF
(load "ex1.sc")
EOF
echo Example 2
mzscheme <<EOF
(load "ex2.sc")
EOF
echo Example 3
../bin/map-closure $OPTIONS ex3
echo Example 4
../bin/map-closure $OPTIONS ex4
echo Example 5
../bin/map-closure $OPTIONS ex5
echo Example 6
../bin/map-closure $OPTIONS ex6
echo Example 7
../bin/map-closure $OPTIONS ex7
echo Example 8
../bin/map-closure $OPTIONS ex8
echo Example 9
../bin/map-closure $OPTIONS ex9
echo Blume Example
../bin/map-closure $OPTIONS blume
echo Ghuloum Example
../bin/map-closure $OPTIONS ghuloum
echo Second Blume Example
../bin/map-closure $OPTIONS blume2
echo Second Ghuloum Example
../bin/map-closure $OPTIONS ghuloum2
echo Third Ghuloum Example
../bin/map-closure $OPTIONS ghuloum3
